### ISSUE TITLE
Default whitespace setting

### ISSUE THREAD

**Issue by rnemec** [atishay/vscode-allautocomplete#1]
Is it correct? It says `[^\\w+]`
I would expect `[^\\w]` or `[^\\w]+` depending on how you use it.

(Side question - in JS, many libs include `$` in the identifiers, so I changed the setting to `[^$\\w]`. Can you confirm that should work fine?)

**Comment by rnemec** [comment]
Thanks. So far the plugin behaves very nicely. Detecting different languages would be great. A step towards this plugin being **a must** for any normal development. Well, even without the languages.

**Comment by atishay** [comment]
Thanks. I have updated this setting. Will add different language basic support as a feature request.

**Comment by atishay** [comment]
Added support for this in 0.0.10
