### ISSUE TITLE
index all file in the workspace

### ISSUE THREAD

**Issue by rmGFW** [atishay/vscode-allautocomplete#101]
support index all file in the workspace not only open file

**Comment by atishay** [comment]
This extension opens the file in VSCode to access its contents. Opening all files will be not sustainable in VSCode. 
If an offline indexing is desired, something like CTags should be used.

**Comment by lakshits11** [comment]
hy can you please help more or give a guide in this direction. I also want to index all files in workspace. ctags is very specific thing and not relevant to a simple web project or a python project etc.

**Comment by lakshits11** [comment]
i am thinking something in direction of using ripgrep etc to index all words present in all documents and then use similar logic from your extension to suggest words
