### ISSUE TITLE
Hyphenated class names

### ISSUE THREAD

**Issue by pavlvs** [atishay/vscode-allautocomplete#14]
It would be useful to have suggestions for hyphenated class names from an HTML file while working in a CSS or JavaScript file that references them. For example: class name="collection-item" appears in CSS and JavaScript suggestions separately as "collection" and "item". It would more useful if it showed as "collection-item" in the list of suggestions.

**Comment by atishay** [comment]
This issue should not be there in the latest version. Please share the values of the following settings if you have overwritten them:

* `AllAutocomplete.whitespace`
* `AllAutocomplete.languageWhitespace`

**Comment by hillcoatt** [comment]
I've got the same problem. I'm on Mac, OSX 11.11.6, VSCode 1.21.1. All hyphenated classes in php or html files won't show up.  Values of the setting you mention:

1.
```
"AllAutocomplete.languageWhitespace": {
    "ruby": "[^\\w\\-_\\$:]+",
    "javascript": "[^\\w_\\$]+",
    "javascriptreact": "[^\\w_\\-\\$\\@]+",
    "typescript": "[^\\w_\\-\\$\\@]+",
    "php": "[^\\w_\\$]+",
    "css": "[^\\w\\-_\\$]+",
    "scss": "[^\\w\\-_\\$\\@]+",
    "html": "[^\\w\\-_\\$]+",
    "python": "[^\\w\\-_]+"
  },
```

2.
```
"AllAutocomplete.whitespace": "[^\\w\\-_\\$]+"
```

**Comment by atishay** [comment]
Can you check updating php to "php" to "[^\\w\\-_\\$]+". That should fit this. I will update the list and create a new version once you can confirm this is not an issue with this setting.

**Comment by hillcoatt** [comment]
I tried replacing with your string. Still doesn't work. And I get an error "Invalid escape character in string". Thanks for trying to sort this out though!

**Comment by hillcoatt** [comment]
I tried to change the order of the regex character list, and now everything works as expected. This is the regex variant in my preferences (switched places for `\\-` and `\\w`) :

    "php": "[^\\-\\w_\\$]+",

**Comment by atishay** [comment]
Updated in 0.0.12. Please reopen if you are still facing issues.
