### ISSUE TITLE
Autocomplete for object members not working

### ISSUE THREAD

**Issue by fregoem** [atishay/vscode-allautocomplete#18]
I installad allautocomplete and it is working fine in blade files but in PHP files it doesn't suggest like in sublime.

Not working:
![error2](https://user-images.githubusercontent.com/33716593/40065376-f1df0e90-5861-11e8-9ea3-7cebeaacb90f.png)

![error](https://user-images.githubusercontent.com/33716593/40065377-f2014b0e-5861-11e8-9e42-9cfa7f91d70b.png)

Working (blade):
![error3](https://user-images.githubusercontent.com/33716593/40065471-31db3f6e-5862-11e8-97bf-4cc4b15c93df.png)

**Comment by atishay** [comment]
@fregoem Can you share a sample file on a gist where I can figure out the issue.

**Comment by fregoem** [comment]
Hi Jain,

Can I send the file via mail?

Kind regards,
Frederiek

Op 15 mei 2018 om 18:50 heeft Atishay Jain <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@fregoem<https://github.com/fregoem> Can you share a sample file on a gist where I can figure out the issue.

**Comment by atishay** [comment]
@fregoem Sure. You can share this to me at `contact[at]atishay[dot]me`. It might take me some time to figure this out but I will get to the bottom of this.

**Comment by atishay** [comment]
@fregoem Please verify version 0.0.13. It should resolve most of the issues.

**Comment by atishay** [comment]
Closing the issue. Please reopen if it re-appears.
