### ISSUE TITLE
Infinite increase in memory

### ISSUE THREAD

**Issue by tiansin** [atishay/vscode-allautocomplete#20]
When I use the php framework to automatically complete, there will be an infinite increase in memory stuck, is the latest version of the emergence of the old version does not have this problem.

**Comment by atishay** [comment]
Thanks for the information. The latest version removed the limits to the list of words shown. I will add it back promptly.

**Comment by atishay** [comment]
@tiansin I have added version 0.0.14 with a new API `AllAutocomplete.maxItemsInSingleList`. This will prevent the autocomplete list from ballooning to all words found in case of a huge list. Unfortunately I don't have a good sample PHP codebase to test with. Please do inform me if this is still an issue for you.

**Comment by tiansin** [comment]
![gif](https://user-images.githubusercontent.com/4232281/40762094-b01dc72c-64d1-11e8-86ca-dce3d6111fcc.gif)

@atishay After my test, I found a reason that this problem occurs when I type > try to list.When I type characters, auto-complete can be quickly listed.

**Comment by atishay** [comment]
@tiansin I have removed `>` character from the autocomplete list in v0.0.15

**Comment by tiansin** [comment]
@atishay 
This problem seems to have been resolved, but there is another phenomenon. When I confirm the completion of the list of items, the preceding characters must be exactly matched for capitalization.Thank!.
![gif](https://user-images.githubusercontent.com/4232281/40784924-9d04565e-6519-11e8-8240-6457206eafbc.gif)

**Comment by atishay** [comment]
Please verify in v0.0.16.

**Comment by atishay** [comment]
Closing this issue. Please reopen if it reappears.
