### ISSUE TITLE
Highlighting words in suggested autocompletions according to syntax of current file.

### ISSUE THREAD

**Issue by oltodosel** [atishay/vscode-allautocomplete#21]
Something similar to the way Atom does it.

**Comment by atishay** [comment]
@oltodosel 
Can you share an example of the desired behavior. Is this something you need in VSCode or the extension? A lot autocomplete values are coming from the language server.

**Comment by oltodosel** [comment]
You know, now that I thought about it some more - I don't really need it.
I was just too accostommed to [Atom's way of indicating](http://7oxfk1.com1.z0.glb.clouddn.com/atom-react-native-autocomplete-demo.gif) autocompletions by color-coding the first letter of property of suggestion. VSCode does it with images instead, and some of them look too bland, so it's kinda harder to discern them.
