### ISSUE TITLE
Auto completion by function name 

### ISSUE THREAD

**Issue by evgygor** [atishay/vscode-allautocomplete#25]
Hi, I'm using this extension for brightscript and I cannot find the option to perform completion by function declaration.

for example i need autocompletion for 'foo' only if the function declaration exists in the file :
```
function foo(bar as string)
    print bar
end function
```
When there no function declaration in current document, or other opened documents - no completion should be suggested

Thanks a lot

**Comment by atishay** [comment]
All autocomplete is built as a dumb word matching system. It does not understand the language semantics. If a word `foo` exists in any of the open documents, it is shown. 

Please reopen the bug if this doe snot answer your question or the extension is behaving erratically.
