### ISSUE TITLE
it can not found in Comment

### ISSUE THREAD

**Issue by suzhenyu22** [atishay/vscode-allautocomplete#26]
when write sql, some infomation in the commnet, it can not be autocomplete.

**Comment by atishay** [comment]
Please share a sample file and a line number where autocomplete is not working.

**Comment by suzhenyu22** [comment]
i am writing sql, when i type code, it can find some similar notes, but when i write the comment, it can't.
is there i miss some setting?

![1](https://user-images.githubusercontent.com/26854721/47400473-e64dcc00-d76f-11e8-9fc4-e0c3e8db00d7.png)

**Comment by atishay** [comment]
Thank you for the screenshot. I will look into the issue

**Comment by atishay** [comment]
<img width="1024" alt="screen shot 2018-11-05 at 9 53 09 pm" src="https://user-images.githubusercontent.com/2279039/48045447-3d2aac80-e145-11e8-92e8-a50fdd2817d3.png">

Seems to be working for me. Can you sand me a sample file where you are having issues. There might be some extension conflicting.

**Comment by suzhenyu22** [comment]
![snipaste_2018-11-06_14-13-31](https://user-images.githubusercontent.com/26854721/48049505-dc00e880-e1d9-11e8-982f-f02b6b5b7010.png)

**Comment by suzhenyu22** [comment]
i read the vscode config setting, i found something , when i change it, all works.
```
  // Controls whether suggestions should automatically show up while typing.
  "editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": false
  }
```
that's why autocomplete not wroks in comments and strings.

**Comment by atishay** [comment]
Wonderful. I will put that in the readme for others.
