### ISSUE TITLE
Freezes 

### ISSUE THREAD

**Issue by AndreyKonogray** [atishay/vscode-allautocomplete#28]
After installation of colorize or all autocomplate, it takes some time and the program hangs, after which the emmet, autocomplete and some other plugins stop working. The problem appears after the finishing of scanning files (on the status bar at the bottom of the workstation)

**Comment by atishay** [comment]
I am not able to reproduce a freeze. It seems colorize overrides all the autocomplete and therefore when it is active nothing else shows up (can be done via the trigger character API). 

But when not doing color everything is working properly. All autocomplete and the language server completions are showing up.

**Comment by atishay** [comment]
Please re-open if you are still facing the issue
