### ISSUE TITLE
Won't autocomplete html when file is associated with Django

### ISSUE THREAD

**Issue by roostercrab** [atishay/vscode-allautocomplete#29]
If an html file is associated with Django instead of html, there is no autocomplete for html offered.

**Comment by atishay** [comment]
It is working for me. Have you disabled autocomplete for django-html file types?
You can do that via `editor.quicksuggestions` for any filetype. See [here](https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense) or https://github.com/atishay/vscode-allautocomplete/issues/6

<img width="1680" alt="screen shot 2019-03-03 at 8 19 32 am" src="https://user-images.githubusercontent.com/2279039/53698115-4c390880-3d8d-11e9-9155-351adf8fa524.png">

**Comment by atishay** [comment]
@roostercrab Please re-open if this is still an issue.
