### ISSUE TITLE
extension seems to disable intellisense and snippts

### ISSUE THREAD

**Issue by jilustrisimo** [atishay/vscode-allautocomplete#3]
This happened in .js and .rb files.  As soon as I disable All Autocomplete everything else works.  I believe from your TODO is already aware of this but if not I think you should know.

**Comment by atishay** [comment]
This is the design on VSCode https://github.com/Microsoft/vscode/issues/4791. I am trying to find a workaround.

**Comment by rnemec** [comment]
@atishay , I just had to disable all-autocomplete too, like @jilustrisimo did. I cannot get any snippets or intellisense going (.JS and .HTML/.CSS). That's sad.

**Comment by atishay** [comment]
@rnemec You can remove the trigger characters but that will not give results in a lot of cases. I have replied to the VSCode bug. Don't know if they will fix it.

**Comment by bpartridge** [comment]
Could we allow the user to specify which scopes they want to have AllAutocomplete active for, defaulting to `['*']`? Then the user could set it to the same specificity as e.g. the Python plugins, restart their editor, and then it would show up in parallel? We could even set sane defaults i.e. Python and JS, while letting the user add whatever esoteric languages they might want to mix AllAutocomplete suggestions in with.

**Comment by atishay** [comment]
I have created a new build based on the suggestions. I have removed the trigger characters and added support for all languages. If everyone finds this good, I will close this bug.

**Comment by atishay** [comment]
Here is the new logic:
* It searches for all languages that vscode knows about.
* Then it registers itself at score 10 for all languages. 

It returns it results and assumes VSCode merges it. 

We have in this process made the scoring logic in VSCode useless, but as a workaround, this does not seem very bad.

**Comment by atishay** [comment]
Closing the issue as no further complaints
