### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by SaoYan** [atishay/vscode-allautocomplete#30]
- Issue Type: `Performance`
- Extension Name: `All-Autocomplete`
- Extension Version: `0.0.18`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/yiqiy/Atishay-Jain.All-Autocomplete-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by atishay** [comment]
@SaoYan Please attach the cpu profile.
