### ISSUE TITLE
An annoying thing width upcase

### ISSUE THREAD

**Issue by netmou** [atishay/vscode-allautocomplete#31]
![0V2pCmgrX2](https://user-images.githubusercontent.com/7068058/56842923-2df31300-68cd-11e9-8eeb-e1cb07acd1d4.gif)
for php code the "accessAllowedCheck" is right, but autocomplete return  accessallowedCheck 
sorry my English is not good!

**Comment by atishay** [comment]
@netmou I am not able to see the issue. There might be a conflicting plugin. Please list the PH plugins in use.

![Screenshot](https://user-images.githubusercontent.com/2279039/58970124-a4591f80-876d-11e9-96ec-5cbb2541bccb.gif)

**Comment by netmou** [comment]
The follow image show All plugins that i used .
![image](https://user-images.githubusercontent.com/7068058/58998711-c8336880-8834-11e9-907e-a8b9d0b599e9.png)

**Comment by netmou** [comment]
The issue has disappeared when I make PHP DocBlocker disabled, thanks
