### ISSUE TITLE
[Feature Request] Disable all-autocomplete for specific languages or files

### ISSUE THREAD

**Issue by jvilk-stripe** [atishay/vscode-allautocomplete#48]
`excludeFiles` excludes certain files from being indexed, but would it be possible to exclude files from receiving autocomplete results this extension?

The context is a repository containing files in multiple programming languages. Some have great autocomplete provided via language servers, others don't. We'd like to use this extension for the latter category of programming languages _without_ it activating on the former category of programming languages, as it clutters the autocomplete results.

Could you add this feature, or would you accept it in a pull request? Thanks!

**Comment by jvilk-stripe** [comment]
e.g.:

```
AllAutocomplete.disabledFiles: "**/*.js"
```

or

```
AllAutocomplete.disabledLanguages: ["javascript"]
```

**Comment by atishay** [comment]
Happy to take a pull request.

**Comment by jvilk-stripe** [comment]
> There is already support for AllAutocomplete.excludeFiles for glob of files to be excluded.

But this excludes files from being indexed. Those files still receive autocomplete results from other files, correct?

**Comment by atishay** [comment]
I have added support for `AllAutocomplete.dontContributeToSelf`, `AllAutocomplete.nonContributingToSelfLanguages, and `AllAutocomplete.nonContributingLanguages`. Please reopen if those options don't meet the requirements.

**Comment by jvilk-stripe** [comment]
Thank you for being so responsive! I'll let you know if we have any trouble with it.
