### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by ceciliassis** [atishay/vscode-allautocomplete#5]
SO: Manjaro 17.0.1 Gellivara
Kernel: x86_64 Linux 4.9.33-1-MANJARO
Visual Studio Code Version: 1.13.1

Problem:
When I try to use the plugin I get this error:

> command 'AllAutocomplete.toggleCurrentFile' not found
> command 'AllAutocomplete.cycleDocuments' not found

All other plugins work!

Attached my installed extentions and the error message.
![screenshot_2017-06-21_10-49-12](https://user-images.githubusercontent.com/9968803/27387505-4af9eaa4-566f-11e7-9b77-443c63642277.png)

**Comment by ngpham** [comment]
This is an issue with file name typo. In the mean time, you can manually fix it by:
- Change to the extension folder, I assume this location for Linux: ~/.vscode/extensions/Atishay-Jain.all-autocomplete-0.0.8
- Under ./out/src/ rename "settings.js" into "Settings.js".

**Comment by akalightowl** [comment]
Have the same problem and you solution help me. Thanks. Maybe should rename this file on repo? Thank you again.

**Comment by atishay** [comment]
@ceciliassis @akalightowl Sorry for the late response. I was out on a vacation. Can you check the fix in version 0.0.9
