### ISSUE TITLE
When fetching a method or function from different file- AllAutoComplete doesn't respect case sensitivity upon autocompleting.

### ISSUE THREAD

**Issue by NikolaKrstic94** [atishay/vscode-allautocomplete#72]
As stated above, the completed word is in lowercase while it should maintain and respect the case sensitivity of the word it's referencing.

**Comment by NikolaKrstic94** [comment]
You can remove this: It was the PHP INTELEPHENSE extension that caused the issue.

**Comment by JohnnyWoong** [comment]
> You can remove this: It was the PHP INTELEPHENSE extension that caused the issue.

im using  PHP INTELEPHENSE and allautocomplete, but its conflicts, how do you solve that?

**Comment by atishay** [comment]
Cannot do something about another extension.
