### ISSUE TITLE
Project wide configuration

### ISSUE THREAD

**Issue by meherranjan** [atishay/vscode-allautocomplete#8]
It would be nice to have a configuration based on directories. For example, let autocomplete suggest based on the current directory level or one level up or project wide.

**Comment by atishay** [comment]
The open tabs have acted as a good way of keeping the list of files to search the words from. Having a list of files outside this will have a performance impact and the extension will need to do a lot more at detecting changes. I will need to test out extensively how much the extension can handle. Will keep this bug open until I have a good solution.

**Comment by mikew** [comment]
Isn't this pretty much ctags?

**Comment by atishay** [comment]
@mikew The feature may be similar but it is not sharing any code with ctags. This plugin is not accessing any files directly and runs completely within the VSCode shell using the VSCode API. I do not intend to break the sandbox with this plugin. If you want ctags, use https://marketplace.visualstudio.com/items?itemName=jaydenlin.ctags-support.

**Comment by mikew** [comment]
Oh I'm aware of all that stuff, my point was that @meherranjan could get what they're looking for with ctags.

**Comment by atishay** [comment]
Added support for `AllAutocomplete.wordListFiles` where you can specify the list of files to open. You can use recursive listing of directory and add that to settings. VSCode does open those files so there is cost involved.

**Comment by mqklin** [comment]
> https://marketplace.visualstudio.com/items?itemName=jaydenlin.ctags-support

@atishay what do u mean by "recursive listing"? Can I use a glob pattern? I was to autocomplete from all files in a project except `node_modules`, and don't care about performance.

**Comment by atishay** [comment]
Use ‘find Directory_name -print’ or ‘ls -R’

**Comment by mqklin** [comment]
> Use ‘find Directory_name -print’ or ‘ls -R’

I see what you mean! I finally used "Open All Files" extension. I open all "*.js* files in my project, then I split my editor and then maximise my 2nd workspace.
